name: vure_dashboard
description: A new Flutter project
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.3
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1

flutter:
  assets:
    - assets/logo.png

flutter_icons:
  android: true
  ios: false
  image_path: assets/logo.png
