name: vure_dashboard
description: A new Flutter project
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.3
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.3.0
flutter:
  assets:
    - assets/logo.png

dev_dependencies:
  flutter_test:
    sdk: flutter
